Vagrant.configure(2) do |config|
  config.vm.box = 'alpine-3.15-amd64'
  #config.vm.box = 'alpine-3.15-uefi-amd64'

  config.vm.hostname = 'example.test'

  config.vm.provider 'libvirt' do |lv, config|
    lv.default_prefix = File.basename(File.dirname(File.dirname(__FILE__)))
    lv.memory = 4*1024
    lv.cpus = 4
    lv.cpu_mode = 'host-passthrough'
    lv.nested = false
    lv.keymap = 'pt'
  end

  config.vm.provider 'virtualbox' do |vb|
    vb.linked_clone = true
    vb.memory = 4*1024
    vb.cpus = 4
  end

  config.vm.provision 'shell', inline: 'uname -a'
  config.vm.provision 'shell', inline: 'cat /etc/alpine-release'
  config.vm.provision 'shell', inline: 'cat /etc/os-release'
  config.vm.provision 'shell', inline: 'lsblk -x KNAME -o KNAME,SIZE,TRAN,SUBSYSTEMS,FSTYPE,UUID,LABEL,MODEL,SERIAL'
  config.vm.provision 'shell', inline: 'df -h'
  # create a netboot image.
  # see https://wiki.alpinelinux.org/wiki/How_to_make_a_custom_ISO_image_with_mkimage
  config.vm.provision 'shell', reset: true, inline: '''
    set -euxo pipefail
    adduser vagrant abuild
    apk update
    apk add alpine-sdk build-base apk-tools alpine-conf busybox fakeroot syslinux xorriso squashfs-tools sudo
    apk add mtools dosfstools grub-efi
    '''
  config.vm.provision 'shell', privileged: false, inline: '''
    set -euxo pipefail
    abuild-keygen -i -a -n
    git clone --branch=3.15-stable --single-branch --depth=1 https://gitlab.alpinelinux.org/alpine/aports.git
    ~/aports/scripts/mkimage.sh --help || true # and check the available profiles.
    ~/aports/scripts/mkimage.sh \
      --repository http://mirrors.dotsrc.org/alpine/v3.15/main \
      --arch x86_64 \
      --profile netboot \
      --tag v3.15 \
      --outdir ~/images
    # show the created files, and the contents of the initramfs and rootfs.
    find ~/images -type f | xargs ls -laF
    zcat ~/images/netboot-v3.15/initramfs-lts | cpio -vt
    unsquashfs -ll ~/images/netboot-v3.15/modloop-lts
    '''
end
