Vagrant.configure(2) do |config|
  config.vm.box = 'alpine-3.13-amd64'

  config.vm.hostname = 'example.test'

  config.vm.provider 'libvirt' do |lv, config|
    lv.default_prefix = File.basename(File.dirname(File.dirname(__FILE__)))
    lv.memory = 2*1024
    lv.cpus = 2
    lv.cpu_mode = 'host-passthrough'
    lv.nested = false
    lv.keymap = 'pt'
  end

  config.vm.provider 'virtualbox' do |vb|
    vb.linked_clone = true
    vb.memory = 2*1024
    vb.cpus = 2
  end

  config.vm.provision 'shell', inline: 'uname -a'
  config.vm.provision 'shell', inline: 'cat /etc/alpine-release'
  config.vm.provision 'shell', inline: 'cat /etc/os-release'
  config.vm.provision 'shell', inline: 'lsblk -x KNAME -o KNAME,SIZE,TRAN,SUBSYSTEMS,FSTYPE,UUID,LABEL,MODEL,SERIAL'
  config.vm.provision 'shell', inline: 'df -h'
end
